class TestErrorInfo:
    line_number: int

    def __init__(self, error: Exception):
        pass
